# Generated by Django 5.0.7 on 2025-10-10 12:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('instituicao', models.CharField(blank=True, choices=[('UNB', 'UnB'), ('IFB', 'IFB'), ('CEUB', 'CEUB'), ('IESB', 'IESB'), ('UCB', 'UCB'), ('OUTRA', 'Outra')], help_text='Obrigatório para perfis ALUNO e PROFESSOR.', max_length=20, null=True)),
                ('perfil', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ORGANIZADOR', 'Organizador'), ('ADMIN', 'Admin')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop'), ('MINICURSO', 'Minicurso'), ('SEMINARIO', 'Seminário'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('local', models.CharField(max_length=150)),
                ('capacidade', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(limit_choices_to=models.Q(('perfil__in', ['ADMIN', 'ORGANIZADOR'])), on_delete=django.db.models.deletion.PROTECT, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_inicio', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('presenca_confirmada', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='api.evento')),
                ('participante', models.ForeignKey(limit_choices_to=models.Q(('perfil__in', ['ALUNO', 'PROFESSOR'])), on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('carga_horaria', models.PositiveIntegerField(help_text='Carga horária em horas.')),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('emitido_por', models.ForeignKey(limit_choices_to=models.Q(('perfil__in', ['ADMIN', 'ORGANIZADOR'])), on_delete=django.db.models.deletion.PROTECT, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='api.inscricao')),
            ],
            options={
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['perfil'], name='api_usuario_perfil_685721_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('perfil__in', ['ALUNO', 'PROFESSOR']), _negated=True), models.Q(('instituicao__isnull', False), models.Q(('instituicao', ''), _negated=True)), _connector='OR'), name='instituicao_required_for_aluno_prof'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_inicio'], name='api_evento_data_in_cd2d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo'], name='api_evento_tipo_64548b_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['organizador'], name='api_evento_organiz_99217b_idx'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='evento_data_fim_gte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('capacidade__gt', 0)), name='capacidade_positive'),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['evento', 'status'], name='api_inscric_evento__09faa0_idx'),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['participante'], name='api_inscric_partici_dcf9fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDENTE', 'CONFIRMADA', 'CANCELADA'])), name='inscricao_status_valido'),
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('evento', 'participante')},
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['codigo'], name='api_certifi_codigo_d298cd_idx'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['emitido_por'], name='api_certifi_emitido_2047fb_idx'),
        ),
    ]
