# Generated by Django 5.0.7 on 2025-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evento_banner_evento_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
