# Generated by Django 5.0.7 on 2025-12-01 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, help_text='Professor responsável pelo evento', limit_choices_to=models.Q(('perfil', 'PROFESSOR')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
