# Generated by Django 5.0.7 on 2025-12-01 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_evento_professor_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('USUARIO_CRIADO', 'Usuário Criado'), ('USUARIO_ATUALIZADO', 'Usuário Atualizado'), ('EVENTO_CRIADO', 'Evento Criado'), ('EVENTO_ATUALIZADO', 'Evento Atualizado'), ('EVENTO_EXCLUIDO', 'Evento Excluído'), ('EVENTO_CONSULTADO_API', 'Evento Consultado via API'), ('INSCRICAO_CRIADA', 'Inscrição Criada'), ('INSCRICAO_ATUALIZADA', 'Inscrição Atualizada'), ('INSCRICAO_CANCELADA', 'Inscrição Cancelada'), ('CERTIFICADO_GERADO', 'Certificado Gerado'), ('CERTIFICADO_CONSULTADO', 'Certificado Consultado'), ('CERTIFICADO_CONSULTADO_API', 'Certificado Consultado via API'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], help_text='Tipo de ação realizada', max_length=50)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP de onde a ação foi realizada', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent do navegador/cliente', max_length=255)),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados adicionais sobre a ação', null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, help_text='Data e hora da ação')),
                ('certificado', models.ForeignKey(blank=True, help_text='Certificado relacionado à ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to='api.certificado')),
                ('evento', models.ForeignKey(blank=True, help_text='Evento relacionado à ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to='api.evento')),
                ('inscricao', models.ForeignKey(blank=True, help_text='Inscrição relacionada à ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to='api.inscricao')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria', to=settings.AUTH_USER_MODEL)),
                ('usuario_afetado', models.ForeignKey(blank=True, help_text='Usuário afetado pela ação (ex: usuário criado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditoria_afetado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['-data_hora'], name='api_auditlo_data_ho_9df599_idx'), models.Index(fields=['acao'], name='api_auditlo_acao_8eb13c_idx'), models.Index(fields=['usuario'], name='api_auditlo_usuario_e7d75b_idx'), models.Index(fields=['evento'], name='api_auditlo_evento__c4d200_idx'), models.Index(fields=['data_hora', 'usuario'], name='api_auditlo_data_ho_d77d6b_idx'), models.Index(fields=['data_hora', 'evento'], name='api_auditlo_data_ho_1225b6_idx')],
            },
        ),
    ]
