# Generated by Django 5.0.7 on 2025-12-04 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='emitido_por',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('perfil__in', ['ADMIN', 'ORGANIZADOR'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('perfil__in', ['ADMIN', 'ORGANIZADOR'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, help_text='Professor responsável pelo evento', limit_choices_to=models.Q(('perfil', 'PROFESSOR')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
