# Generated by Django 6.0 on 2025-12-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_certificado_emitido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=4, help_text='Carga horária do evento em horas'),
        ),
    ]
