# Generated by Django 6.0 on 2025-12-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_evento_carga_horaria'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='certificado',
            name='api_certifi_codigo_d298cd_idx',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='codigo',
        ),
    ]
